Update benchmark.yml

diff --git a/.github/workflows/benchmark.yml b/.github/workflows/benchmark.yml
--- a/.github/workflows/benchmark.yml
+++ b/.github/workflows/benchmark.yml
@@ -3,7 +3,7 @@ name: Run benchmark
 on:
   workflow_dispatch:
 jobs:
-  build-and-run:
+  run-bench:
     runs-on: ubuntu-latest
     container:
       image: alexandermey/distirbutedmastservice:env1
@@ -24,22 +24,22 @@ jobs:
           cmake -G Ninja \
           ../src/
           ninja
-      - name : draw flamegraphs
-        if: success() || failure()
-        run: |
-           cd ${GITHUB_WORKSPACE}/build/computationalNode
-           git clone https://github.com/brendangregg/FlameGraph
-           mkdir FlameGraph/res && cd FlameGraph/res
-           perf record --call-graph dwarf ./../../test/samplePerExample
-           perf script | ../stackcollapse-perf.pl |../flamegraph.pl > perf.svg
-      - name: Save flame graphs and perf files
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: flameGraphs
-          path: /__w/distributedMathArh/distributedMathArh/build/computationalNode/FlameGraph/res
-          if-no-files-found: warn
-          include-hidden-files: true
+#      - name : draw flamegraphs
+#        if: success() || failure()
+#        run: |
+#           cd ${GITHUB_WORKSPACE}/build/computationalNode
+#           git clone https://github.com/brendangregg/FlameGraph
+#           mkdir FlameGraph/res && cd FlameGraph/res
+#           perf record --call-graph dwarf ./../../test/samplePerExample
+#           perf script | ../stackcollapse-perf.pl |../flamegraph.pl > perf.svg
+#      - name: Save flame graphs and perf files
+#        if: success() || failure()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: flameGraphs
+#          path: /__w/distributedMathArh/distributedMathArh/build/computationalNode/FlameGraph/res
+#          if-no-files-found: warn
+#          include-hidden-files: true
       - name: Run benchmark
         if: success() || failure()
         run: |
